# Generated by Django 4.2.5 on 2023-11-25 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categiry',
            new_name='Category',
        ),
    ]
